name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar c贸digo do reposit贸rio
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build com Maven
        run: mvn clean install --batch-mode

      - name: Executar Testes
        run: mvn test --batch-mode

      - name: Gerar Relat贸rio de Cobertura
        run: mvn jacoco:report --batch-mode

      - name: Publicar Relat贸rio de Cobertura
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: cobertura-de-codigo
          path: target/site/jacoco
