name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar c贸digo do reposit贸rio
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build com Maven
        run: mvn clean install

      - name: Executar Testes
        run: mvn test

      - name: Gerar Relat贸rio de Cobertura
        run: mvn jacoco:report

      - name: Publicar Relat贸rio de Cobertura
        uses: actions/upload-artifact@v3
        with:
          name: cobertura-de-codigo
          path: target/site/jacoco
